version: 2

build:
  os: "ubuntu-24.04"
  tools:
    nodejs: "22"
  commands:
    - npm ci
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - BASE_URL="/$READTHEDOCS_LANGUAGE/$READTHEDOCS_VERSION" npm run myst -- build -d --html
    - cp -a _build/html/. "$READTHEDOCS_OUTPUT/html"
    - rm -r _build
